version: '3.8'

services:
  db:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017
      - DB_NAME=Ecommerce_Store
      - PORT=5000
      - PRODUCT_PER_PAGE=8
      - STRIPE_KEY=
      - MAIL_ADDRESS=
      - MAIL_PASSWORD=
      - UPLOAD_PRESET=digikaan
      - CLOUD_NAME=
      - CLOUD_API_SECRET=
      - CLOUD_API_KEY=
      - DOMAIN=http://localhost:3000
      - FRONTEND_DOMAIN=http://localhost:5173
    ports:
      - "3000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - VITE_FIREBASE_KEY=
        - VITE_AUTH_DOMAIN=
        - VITE_PROJECT_ID=
        - VITE_STORAGE_BUCKET=
        - VITE_MESSAGING_SENDER_ID=
        - VITE_APP_ID=
        - VITE_MEASUREMENT_ID
        - VITE_SERVER=http://localhost:3000
        - VITE_STRIPE_PROMISE=
    depends_on:
      - backend
    ports:
      - "5173:3000"
    restart: unless-stopped

volumes:
  mongodbdata: