FROM node:23.8.0-alpine AS builder

WORKDIR /usr/src/app

COPY server/package.json package.json
COPY server/package-lock.json package-lock.json

RUN npm install

COPY server/ .

RUN npm run build

FROM node:23.8.0-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/package.json ./
COPY --from=builder /usr/src/app/package-lock.json ./

RUN npm install

CMD ["npm","run","start"]